#!/bin/sh

. /lib/functions.sh

include /lib/upgrade

v "Checking image..."
platform_check_image "$IMAGE"

v "Performing system upgrade..."
if type 'platform_do_upgrade' >/dev/null 2>/dev/null; then
	platform_do_upgrade "$IMAGE"
else
	default_do_upgrade "$IMAGE"
fi

if [ -n "$UPGRADE_BACKUP" ] && type 'platform_copy_config' >/dev/null 2>/dev/null; then
	platform_copy_config
fi

v "Upgrade completed"
sleep 1; sync

INTERACTIVE=1 ask_bool 0 "Run /etc/reboot.sh now?" && /etc/reboot.sh
