#!/bin/sh

. /lib/functions.sh

include /lib/upgrade

test_continue()
{
	echo -n "Run $1 now (y/n)? "
	read answer

	if echo -n $answer | grep -i -q '^y$'; then
		echo "Launching $1"
		eval $1
	else
		echo "Not doing $1"
	fi
}

v "Checking image..."
platform_check_image "$IMAGE"

v "Performing system upgrade..."
if type 'platform_do_upgrade' >/dev/null 2>/dev/null; then
	platform_do_upgrade "$IMAGE"
else
	default_do_upgrade "$IMAGE"
fi

if [ -n "$UPGRADE_BACKUP" ] && type 'platform_copy_config' >/dev/null 2>/dev/null; then
	platform_copy_config
fi

v "Upgrade completed"
sleep 1

sync
grep -q 'root=PARTLABEL=openwrt_rootfs_alt' /proc/cmdline && _alt= || _alt=_alt
CMDLINE="root=PARTLABEL=openwrt_rootfs$_alt $( cat /proc/cmdline | sed -e 's:BOOT_IMAGE=[^ ]\+ root=[^ ]\+ ::' )"
test_continue "/etc/init.d/kdump stop; kexec -f /boot/vmlinuz$_alt --command-line=$CMDLINE"
